Repository hpi-swt2/compass-portal-red, pull requests merged in 2021-12, with the labels that each got.

#35 Add scraping task
  lib/tasks/scraper.rake
Labels: Datenkrake (BA)

#42 Single Page Scraping
  '
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/images/people/.gitkeep
  app/assets/stylesheets/people.scss
  app/assets/stylesheets/person_urls.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/people_controller.rb
  app/controllers/person_urls_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/helpers/people_helper.rb
  app/helpers/person_urls_helper.rb
  app/models/person.rb
  app/models/person_url.rb
  app/views/people/_form.html.erb
  app/views/people/_person.json.jbuilder
  app/views/people/edit.html.erb
  app/views/people/index.html.erb
  app/views/people/index.json.jbuilder
  app/views/people/new.html.erb
  app/views/people/show.html.erb
  app/views/people/show.json.jbuilder
  app/views/person_urls/_person_url.json.jbuilder
  app/views/person_urls/index.json.jbuilder
  app/views/person_urls/show.json.jbuilder
  config/routes.rb
  db/migrate/20211123131100_create_people.rb
  db/migrate/20211130185202_create_person_urls.rb
  db/schema.rb
  lib/scraping/hpi_data_collector.rb
  lib/scraping/hpi_paragraph_scraper.rb
  lib/scraping/hpi_table_scraper.rb
  lib/scraping/hpi_web_scraper.rb
  lib/scraping/scraping_exception.rb
  spec/factories/people.rb
  spec/factories/person_urls.rb
  spec/features/users/openid_connect_sign_in_spec.rb
  spec/helpers/people_helper_spec.rb
  spec/models/person_spec.rb
  spec/models/person_url_spec.rb
  spec/requests/people_spec.rb
  spec/routing/people_routing_spec.rb
  spec/routing/person_urls_routing_spec.rb
  spec/scraper/hpi_data_collector_spec.rb
  spec/scraper/html_mocks/multiple_people.html
  spec/scraper/html_mocks/paragraph.html
  spec/scraper/html_mocks/table.html
  spec/views/people/edit.html.erb_spec.rb
  spec/views/people/index.html.erb_spec.rb
  spec/views/people/new.html.erb_spec.rb
  spec/views/people/show.html.erb_spec.rb
Labels: Datenkrake (BA)

#67 Datenkrake Scraper
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/assets/images/people/.gitkeep
  app/assets/stylesheets/people.scss
  app/assets/stylesheets/person_urls.scss
  app/assets/stylesheets/scaffolds.scss
  app/controllers/people_controller.rb
  app/controllers/person_urls_controller.rb
  app/helpers/people_helper.rb
  app/helpers/person_urls_helper.rb
  app/models/information.rb
  app/models/person.rb
  app/models/person_url.rb
  app/models/room.rb
  app/views/people/_form.html.erb
  app/views/people/_person.json.jbuilder
  app/views/people/edit.html.erb
  app/views/people/index.html.erb
  app/views/people/index.json.jbuilder
  app/views/people/new.html.erb
  app/views/people/show.html.erb
  app/views/people/show.json.jbuilder
  app/views/person_urls/_person_url.json.jbuilder
  app/views/person_urls/index.json.jbuilder
  app/views/person_urls/show.json.jbuilder
  config/routes.rb
  db/migrate/20211130185202_create_person_urls.rb
  db/schema.rb
  lib/scraping/hpi_data_collector.rb
  lib/scraping/hpi_paragraph_scraper.rb
  lib/scraping/hpi_table_scraper.rb
  lib/scraping/hpi_web_scraper.rb
  lib/scraping/scraper.rb
  lib/scraping/scraping_exception.rb
  lib/tasks/scraper.rake
  public/assets/images/people/.gitkeep
  spec/factories/person_urls.rb
  spec/features/users/openid_connect_sign_in_spec.rb
  spec/helpers/people_helper_spec.rb
  spec/models/person_url_spec.rb
  spec/requests/people_spec.rb
  spec/routing/people_routing_spec.rb
  spec/routing/person_urls_routing_spec.rb
  spec/scraper/hpi_data_collector_spec.rb
  spec/scraper/html_mocks/multiple_people.html
  spec/scraper/html_mocks/paragraph.html
  spec/scraper/html_mocks/table.html
  spec/views/people/edit.html.erb_spec.rb
  spec/views/people/index.html.erb_spec.rb
  spec/views/people/new.html.erb_spec.rb
  spec/views/people/show.html.erb_spec.rb
Labels: Datenkrake (BA)

#90 74 import script
  app/assets/data/importBuilding1.csv
  app/assets/data/importBuilding1.gpx
  app/helpers/README.md
  app/helpers/import_gpx.rb
  app/helpers/import_rooms.rb
  app/helpers/indoor_helper.rb
  spec/helpers/indoor_helper_spec.rb
Labels: Indoor Map

#92 65 display search entry icon
  app/assets/stylesheets/search.scss
  app/models/searchable_record.rb
  app/views/search/index.html.erb
  spec/features/search/access_search_page_spec.rb
Labels: Search
